## Docker Compose 
version: '3.4'
services:

   
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
     
    ports:
      - 80:80
    
